#!/usr/bin/env python3
"""Generate public catalog documentation from skills.json."""

from __future__ import annotations

import argparse
import json
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Sequence


ROOT = Path(__file__).resolve().parents[1]
README_START = "<!-- skills-table:start -->"
README_END = "<!-- skills-table:end -->"


class CatalogError(ValueError):
    """A user-facing catalog generation error."""


def load_catalog(root: Path) -> list[dict[str, object]]:
    path = root / "skills.json"
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise CatalogError(f"Catalog not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise CatalogError(
            f"Invalid JSON in {path}: line {exc.lineno}, column {exc.colno}"
        ) from exc
    if not isinstance(document, dict) or document.get("schema_version") != 2:
        raise CatalogError("skills.json must use schema_version 2")
    skills = document.get("skills")
    if not isinstance(skills, list) or not all(isinstance(item, dict) for item in skills):
        raise CatalogError("skills.json must contain a skills array of objects")
    return skills


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def _requirements(item: dict[str, object]) -> str:
    values = item.get("requirements", [])
    if not isinstance(values, list) or not values:
        return "None"
    return "<br>".join(_cell(value) for value in values)


def render_readme_table(skills: Sequence[dict[str, object]]) -> str:
    lines = [
        "| Goal | Skill | Extra requirements | Source |",
        "|---|---|---|---|",
    ]
    for item in skills:
        name = str(item["name"])
        path = str(item["path"])
        lines.append(
            "| {category} | [`{name}`]({path}) | {requirements} | `{provenance}` |".format(
                category=_cell(item["category"]),
                name=_cell(name),
                path=path,
                requirements=_requirements(item),
                provenance=_cell(item["provenance"]),
            )
        )
    return "\n".join(lines)


def replace_readme_section(readme: str, generated: str) -> str:
    if readme.count(README_START) != 1 or readme.count(README_END) != 1:
        raise CatalogError(
            f"README.md must contain exactly one {README_START!r} and {README_END!r} marker"
        )
    start = readme.index(README_START)
    end = readme.index(README_END)
    if start >= end:
        raise CatalogError("README.md catalog markers are in the wrong order")
    prefix = readme[: start + len(README_START)].rstrip()
    suffix = readme[end:].lstrip()
    return f"{prefix}\n\n{generated.rstrip()}\n\n{suffix}"


def _doc_link(url: str) -> str:
    if not url:
        return ""
    if url.startswith(("https://", "http://")):
        return url
    return f"../{url}"


def render_catalog_document(skills: Sequence[dict[str, object]]) -> str:
    categories: OrderedDict[str, list[dict[str, object]]] = OrderedDict()
    for item in skills:
        categories.setdefault(str(item["category"]), []).append(item)

    lines = [
        "# Skill Catalog",
        "",
        "<!-- Generated by scripts/catalog.py from skills.json. Do not edit by hand. -->",
        "",
        "This is the detailed companion to the catalog in the main README. See",
        "[USAGE.md](USAGE.md) for workflow examples and [NOTICE.md](../NOTICE.md)",
        "for licensing and provenance details.",
    ]
    for category, items in categories.items():
        lines.extend(["", f"## {category}"])
        for item in items:
            name = str(item["name"])
            description = str(item["description"])
            tags = item.get("tags", [])
            requirements = item.get("requirements", [])
            provenance = str(item["provenance"])
            source_url = str(item.get("source_url", ""))
            revision = str(item.get("source_revision", ""))
            notice_path = str(item["notice_path"])

            lines.extend(
                [
                    "",
                    f"### [`{name}`](../{item['path']})",
                    "",
                    description,
                    "",
                    f"- Tags: {', '.join(f'`{tag}`' for tag in tags)}",
                    "- Requirements: "
                    + (
                        "; ".join(str(requirement) for requirement in requirements)
                        if requirements
                        else "none beyond the tools needed for the task"
                    ),
                    f"- Provenance: `{provenance}`",
                ]
            )
            if source_url:
                label = f"pinned source `{revision[:12]}`" if revision else "source map"
                lines.append(f"- Source: [{label}]({_doc_link(source_url)})")
            else:
                lines.append("- Source: original project work")
            lines.extend(
                [
                    f"- License: `{item['license_spdx']}`; see [notice](../{notice_path})",
                    "",
                    "```text",
                    str(item["example_prompt"]),
                    "```",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def generate(root: Path, *, check: bool) -> int:
    skills = load_catalog(root)
    readme_path = root / "README.md"
    docs_path = root / "docs" / "SKILL_CATALOG.md"
    try:
        current_readme = readme_path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise CatalogError(f"README not found: {readme_path}") from exc

    expected_readme = replace_readme_section(current_readme, render_readme_table(skills))
    expected_docs = render_catalog_document(skills)
    current_docs = docs_path.read_text(encoding="utf-8") if docs_path.exists() else ""

    stale: list[Path] = []
    if current_readme != expected_readme:
        stale.append(readme_path)
    if current_docs != expected_docs:
        stale.append(docs_path)

    if check:
        if stale:
            for path in stale:
                print(f"out of date: {path.relative_to(root)}", file=sys.stderr)
            print("Run: python scripts/catalog.py", file=sys.stderr)
            return 1
        print("Catalog documentation is up to date.")
        return 0

    if readme_path in stale:
        readme_path.write_text(expected_readme, encoding="utf-8", newline="\n")
        print(f"updated: {readme_path.relative_to(root)}")
    if docs_path in stale:
        docs_path.parent.mkdir(parents=True, exist_ok=True)
        docs_path.write_text(expected_docs, encoding="utf-8", newline="\n")
        print(f"updated: {docs_path.relative_to(root)}")
    if not stale:
        print("Catalog documentation is already up to date.")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Fail if generated files differ.")
    mode.add_argument(
        "--write",
        action="store_true",
        help="Write generated files (the default; provided for explicit scripts).",
    )
    parser.add_argument(
        "--root", type=Path, default=ROOT, help=argparse.SUPPRESS
    )
    args = parser.parse_args(argv)
    try:
        return generate(args.root.resolve(), check=args.check)
    except (CatalogError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
